# -*- coding: utf-8 -*-
"""Reverse Stabble Diffusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcQ_kWixuAdOu_GDWVfClwTXze0gsBW4

## Reverse Stable Diffusion

1. Open AI's CLIP
2. Salesforce's BLIP


CLIP Interrogator
"""

!pip install clip-interrogator==0.6.0

from PIL import Image
from clip_interrogator import Config, Interrogator

image = Image.open('/content/image_1.jpeg').convert('RGB')

image

from traitlets.traitlets import Integer
ci = Interrogator(Config(clip_model_name='ViT-L-14/openai'))

result = ci.interrogate(image)

print(result)

